import CompetitionHero from "@/components/competitions/CompetitionHero";
import HubReveal from "@/components/competitions/HubReveal";
import Link from "next/link";
import HubEvents from "@/components/competitions/HubEvents";
export const metadata = { title: "Competition Hub | Finesse BJJ", description: "Compete, support the team, and relive the moments with Finesse BJJ." };
export default function CompetitionsPage() {
  return <main className="competition-hub pt-16"><CompetitionHero/><div className="bg-[#CC1122] text-white px-6 py-4 text-center text-sm">LOCAL CONCEPT PREVIEW · Event names, dates, results, and photos below are illustrative.</div><nav aria-label="Competition hub sections" className="border-b border-white/15"><div className="max-w-7xl mx-auto flex flex-wrap gap-7 px-6 py-5 font-headline text-lg tracking-wider"><a href="#events">EVENTS & RESULTS</a><a href="#experience">THE EXPERIENCE</a><a href="#team">SUPPORT THE TEAM</a></div></nav><HubEvents/>
<HubReveal><section id="experience" className="hub-section border-t border-white/15"><p className="hub-eyebrow">BEFORE YOU STEP ON THE MATS</p><h2 className="font-headline text-5xl md:text-6xl mb-9">YOUR FIRST COMPETITION STARTS HERE.</h2><div className="grid md:grid-cols-3 gap-8">{[["01","MAKE A PLAN","Talk with your coach about readiness, divisions, and a realistic goal for your first event."],["02","KNOW THE FORMAT","Check the organizer’s current rules, weigh-in requirements, uniform policy, and registration deadline."],["03","SHOW UP TOGETHER","Pack your gear, confirm the team meetup, and leave time to warm up. Stay to cheer on your teammates."]].map(([number,title,copy]) => <article key={number} className="border-t border-[#CC1122]/60 pt-6"><span className="font-headline text-4xl text-[#CC1122]">{number}</span><h3 className="font-headline text-3xl mt-4 mb-3">{title}</h3><p className="text-zinc-400 leading-relaxed">{copy}</p></article>)}</div></section></HubReveal><HubReveal><section id="team" className="bg-[#CC1122] text-white px-6 py-16"><div className="max-w-7xl mx-auto grid md:grid-cols-2 gap-8 items-center"><div><p className="text-xs font-bold tracking-[.25em] mb-4">YOU DON’T HAVE TO COMPETE TO BE PART OF IT.</p><h2 className="font-headline text-6xl md:text-7xl">WILL YOU BE<br/>IN OUR CORNER?</h2></div><div><p className="text-lg leading-relaxed mb-6">Bring your voice. Bring your family. Come support the athletes representing Finesse and be part of the day.</p><Link href="#events" className="bg-black text-white px-6 py-4 font-headline text-xl inline-block">FIND AN EVENT TO SUPPORT ↗</Link></div></div></section></HubReveal></main>;
}
