"use client";
import { useState } from "react";
import Link from "next/link";
import ParallaxPhoto from "@/components/motion/ParallaxPhoto";
import HubReveal from "./HubReveal";
import { competitions } from "@/lib/competitions";
export default function HubEvents() {
  const [tab, setTab] = useState("upcoming");
  return <section id="events" className="hub-section"><div className="flex flex-wrap items-end justify-between gap-5 mb-8"><div><p className="hub-eyebrow">THE TEAM CALENDAR</p><h2 className="font-headline text-5xl">FIND YOUR NEXT CHALLENGE.</h2></div><div role="tablist" aria-label="Competition events" className="flex border border-white/20">{[["upcoming","UPCOMING"],["past","RESULTS & RECAPS"]].map(([value,label]) => <button role="tab" aria-selected={tab === value} aria-controls="event-list" id={`tab-${value}`} key={value} onClick={() => setTab(value)} className={`px-5 py-3 font-headline tracking-wider ${tab === value ? "bg-[#CC1122] text-white" : "text-zinc-400"}`}>{label}</button>)}</div></div><div id="event-list" role="tabpanel" aria-labelledby={`tab-${tab}`} className="grid md:grid-cols-2 gap-6">{competitions.filter(event => event.status === tab).map((event, index) => <HubReveal key={event.slug} delay={index * 0.12}><Link href={`/competitions/${event.slug}`} className="group block border border-white/15 bg-[#151515] hover:border-[#CC1122] transition-colors"><div className="relative h-64 overflow-hidden"><ParallaxPhoto src={event.image} alt={event.imageAlt} position={event.imagePosition} sizes="(min-width: 768px) 50vw, 100vw" className="absolute inset-0"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent"/><span className="absolute top-5 left-5 bg-[#CC1122] text-white text-xs font-bold px-3 py-2">SAMPLE {event.status === "past" ? "RECAP" : "EVENT"}</span><div className="absolute bottom-5 left-5 bg-black/80 px-4 py-2 text-center"><p className="text-xs tracking-widest text-[#FFB3AD]">{event.month}</p><p className="font-headline text-4xl">{event.day}</p></div></div><div className="p-6"><p className="hub-eyebrow">{event.organizer}</p><h3 className="font-headline text-4xl">{event.name}</h3><p className="text-zinc-400 text-sm mt-2">{event.date} · {event.location}</p><p className="text-zinc-300 mt-4">{event.description}</p><p className="text-[#CC1122] font-headline text-xl mt-6">{event.status === "past" ? "VIEW RESULTS & GALLERY" : "EVENT DETAILS & TEAM SUPPORT"} ↗</p></div></Link></HubReveal>)}</div></section>;
}
